### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by ricardocasaca** [firelab/viirs_ba#18]
I know this is not the place to ask but I have not found another way. Where can I find datasets to use as input in your code?. All I found did not work.

Thanks

**Comment by bnordgren** [comment]
This is a research code which was used with data produced by the direct readout system in Salt Lake City. You may have to do some adapting to get it to work with the production data sets you can find on the web. Note that this isn't production code and it's not supported. Here are some tips: 

-  Data are officially distributed from the [NOAA CLASS site](https://www.class.ngdc.noaa.gov/)
    - Radiance data in each band: search for VIIRS_SDR in the dropdown menu, and make sure you specify to disaggregate data in the advanced options when ordering data (one band per file)
    - 750m Active Fire: Search for JPSS_GRAN in the dropdown menu
- VIIRS 375m active fire from [NASA FIRMS](https://firms.modaps.eosdis.nasa.gov/download/). NOTE you will have to adapt the code to work with a vector product instead of a raster

Depending on the area of the world that's interesting to you, you can check the [USFS GTAC site](https://fsapps.nwcg.gov/afm/gisdata.php) or the [University of Maryland site](http://viirsfire.geog.umd.edu/pages/mapsData.php)

Good luck!

**Comment by ricardocasaca** [comment]
I'll work on it. Thank you for your help.
