### ISSUE TITLE
Copying active fires

### ISSUE THREAD

**Issue by bnordgren** [firelab/viirs_ba#8]
Carl, 

Tell me if my understanding of the following is correct: 

viirs_activefire_2_fireevents exists to copy all of the active fires from a particular satellite timestamp from the active_fire table to the fire_events table. In the process, it reprojects the points. Additionally, it assigns each active fire point to an existing collection or creates a new collection, setting the last_update field appropriately.

The threshold for assimilating points into an existing collection is the same as the specified spatiotemporal thresholds.

I started this thinking that there was a way to simplify, but I think I talked myself out of it now.

**Comment by calbury** [comment]
Yes,
You are correct. I need to go back and look at the “documentation”, I don’t think I documented the db functions very well.
There is the “check_for_activity” that happens first.  Active_fire/thresholded pixels can only be added to an active event. Otherwise a new collection is created (for active_fire) or the pixel is ignored (thresholded)

One thing to be aware of is that I’m using the same temporal threshold to:
- ```
       Determine if a collection is still active
  ```
- ```
       Determine if a thresholded pixel is valid
  ```
  
  Users might want to be able to use different thresholds for these cases.

[Forest Service Shield]

Carl Albury
Remote Sensing Specialist

Forest Service Contractor
Remote Sensing Applications Center

p: 801-975-3351
calbury@fs.fed.usmailto:calbury@fs.fed.us

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.ushttp://www.fs.fed.us/
[USDA Logo]http://usda.gov/[Forest Service Twitter]https://twitter.com/forestservice[USDA Facebook]https://www.facebook.com/pages/US-Forest-Service/1431984283714112

Caring for the land and serving people
